#4 Add getReport method
ripe-tech/epir-papyrus-api-js pull request #1
Opened 2020-09-30 10:00 UTC by 3rdvision

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/epir-core/issues/4 |
| Decisions | • Add `getReport` method instead of mock method. <br> • Add hermes mock order <br> • Adapt example to call `getReport`.  |

2020-09-30 10:13 UTC, gcandal requested changes

2020-09-30 10:13 UTC, gcandal commented on examples/simple.js
> +const baseUrl = "http://localhost:3000/";
Point to now instead

2020-09-30 10:13 UTC, gcandal commented on js/report.js
> +            const reportHtml = await contents.text();
Delete

2020-09-30 10:13 UTC, gcandal commented on mocks/hermes/bastia.json
> +{
Move this inside `examples`

2020-09-30 10:52 UTC, gcandal approved these changes

2020-10-09 18:02 UTC, joamag approved these changes

2020-10-09 18:02 UTC, joamag commented on examples/simple.js
> +const baseUrl = "https://epir-papyrus-now.platforme.com/";
remove base url

2020-10-09 18:02 UTC, merged